Update update-binary

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -564,23 +564,10 @@ do_vendorlevelcheck;
 
 ui_print "Installing...";
 # hack to maintain support for anykernel.sh files that weren't updated correctly along with the AK core
-CORE=$(grep -oE 'ak.*core.sh' anykernel.sh);
+# (hardcoded instead of grep-derived: the old `grep -oE 'ak.*core.sh' anykernel.sh` matched ANY line
+# containing that substring, including comments, and $CORE silently became multiple words whenever
+# anykernel.sh had more than one match -- breaking the `[ -f ]` test below with "binary operator expected")
+CORE=ak3-core.sh;
 [ -f tools/$CORE ] || ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 ash anykernel.sh;
-if [ $? != 0 ]; then
-  abort;
-fi;
-
-do_modules;
-
-debugging;
-ui_print " ";
-restore_env;
-
-if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
-  cleanup;
-fi;
-
-ui_print " " "Done!";
-export PATH="$OLD_PATH";
-unset OLD_PATH OUTFD ZIPFILE;
+if [ $? != 
